//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMovies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardDetail
    {
        public string card_number { get; set; }
        public int customer_id { get; set; }
        public byte exp_month { get; set; }
        public byte exp_year { get; set; }
        public string cvv { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
