//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMovies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Showing
    {
        public int showing_id { get; set; }
        public System.DateTime showing_date { get; set; }
        public int screen { get; set; }
        public int movie_id { get; set; }
    
        public virtual Movy Movy { get; set; }
    }
}
